//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Vue.Fabriques
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
	using Vue.Interfaces;
    using System.Drawing;

	/// <remarks>Fabrique abstraite</remarks>
	/// <remarks>Poids mouche</remarks>
	public class FabriqueVue2D : FabriqueVue
	{
		public virtual void creerLaser()
		{
			throw new System.NotImplementedException();
		}

		public virtual void creerCaseArtefact(int nbArt)
		{
			throw new System.NotImplementedException();
		}

		public virtual void creerVaisseauMere()
		{
			throw new System.NotImplementedException();
		}

		public virtual void creerDes()
		{
			throw new System.NotImplementedException();
		}

		public virtual void creerCaseBase(Color couleur)
		{
			throw new System.NotImplementedException();
		}

		public virtual void creerCaseAsteroide(int[] points)
		{
			throw new System.NotImplementedException();
		}

		public virtual void creerCaseVide()
		{
			throw new System.NotImplementedException();
		}

		public virtual void creerCaseEnergie()
		{
			throw new System.NotImplementedException();
		}

		public virtual void creerBattlecruiser()
		{
			throw new System.NotImplementedException();
		}

		public virtual void creerCapsuleDeSurvie()
		{
			throw new System.NotImplementedException();
		}

		public virtual void creerVueQuitter()
		{
			throw new System.NotImplementedException();
		}

		public virtual void creerCompteurArtefact()
		{
			throw new System.NotImplementedException();
		}

		public virtual void creerCompteurCanon()
		{
			throw new System.NotImplementedException();
		}

	}
}

