//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Controleur.command
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	/// <remarks>commande</remarks>
	public interface Action 
	{
		bool canDo();

		void doIt();

	}
}

