//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Controleur.command
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class LancerPartie : Action
	{
		public virtual bool canDo()
		{
			throw new System.NotImplementedException();
		}

        public virtual void doIt()
		{
			throw new System.NotImplementedException();
		}

	}
}

