//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#pragma once
#define WANTDLLEXP
#ifdef WANTDLLEXP		//exportation dll
#define DLL  __declspec( dllexport )
#define EXTERNC extern "C"
#else
#define DLL		//standard
#define EXTERNC
#endif

#include<vector>

namespace Model
{
	class DLL Artefact
	{
	public:
		Artefact() {}
		~Artefact() {}
	}; 
	EXTERNC DLL Artefact* ARTEFACT_New() { return new Artefact(); }
	EXTERNC DLL void ARTEFACT_Delete(Artefact* obj) { delete obj; }
} 

