//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#pragma once
#define WANTDLLEXP
#ifdef WANTDLLEXP		//exportation dll
#define DLL  __declspec( dllexport )
#define EXTERNC extern "C"
#else
#define DLL		//standard
#define EXTERNC
#endif


#include<vector>

namespace Model
{
	class DLL CanonLaser
	{
		private :
			Vaisseau* vaisseauDuCanon;
			int capaciteEnergie;
			int chargesCanonRestantes;
			int nombreRebondsCanon;
		public :
			CanonLaser() : capaciteEnergie(0), chargesCanonRestantes(0), nombreRebondsCanon(0) {
				vaisseauDuCanon = 0;
			}

			CanonLaser(Vaisseau* v) : capaciteEnergie(0), chargesCanonRestantes(0), nombreRebondsCanon(0) {
				vaisseauDuCanon = v;
			}
			~CanonLaser() {
				if(vaisseauDuCanon)
					delete vaisseauDuCanon;
			}

			virtual void tirer(float angle) {}

	}; 

	//EXTERNC DLL CanonLaser* CANONLASER_New() { return new CanonLaser(); }
	EXTERNC DLL void CANONLASER_Delete(CanonLaser* obj) { delete obj; }
	EXTERNC DLL void CANONLASER_tirer(CanonLaser* c, float angle) { c->tirer(angle); }
} 

