//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#pragma once
#define WANTDLLEXP
#ifdef WANTDLLEXP		//exportation dll
#define DLL  __declspec( dllexport )
#define EXTERNC extern "C"
#else
#define DLL		//standard
#define EXTERNC
#endif
#include "Vaisseau.h"
#include<vector>

namespace Model
{
	class DLL CapsuleDeSurvie : public Vaisseau
	{
	public:
		CapsuleDeSurvie() {}
		~CapsuleDeSurvie() {}
	}; 

	EXTERNC DLL CapsuleDeSurvie* CAPSULEDESURVIE_New() { return new CapsuleDeSurvie(); }
	EXTERNC DLL void CAPSULEDESURVIE_Delete(CapsuleDeSurvie* obj) { delete obj; }
} 

