//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#pragma once
#define WANTDLLEXP
#ifdef WANTDLLEXP		//exportation dll
#define DLL  __declspec( dllexport )
#define EXTERNC extern "C"
#else
#define DLL		//standard
#define EXTERNC
#endif


#include "Case.h"
#include<vector>

namespace Model
{
	class DLL CaseAsteroide : public Case
	{
		private :

			std::vector<float*> formeAsteroide;

		public :
			CaseAsteroide() {}
			~CaseAsteroide() {}
			bool estPleine() { return true; }

	}; 

	//EXTERNC DLL CaseAsteroide* CASEASTEROIDE_New() { return new CaseAsteroide(); }
	EXTERNC DLL void CASEASTEROIDE_Delete(CaseAsteroide* obj) { delete obj; }
	EXTERNC DLL bool CASEASTEROIDE_estPleine(CaseAsteroide* c) { return c->estPleine(); }
	
} 

