//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#pragma once
#define WANTDLLEXP
#ifdef WANTDLLEXP		//exportation dll
#define DLL  __declspec( dllexport )
#define EXTERNC extern "C"
#else
#define DLL		//standard
#define EXTERNC
#endif
#include "Case.h"
#include<vector>

namespace Model
{
	class DLL CaseArtefact : public Case
	{
	public :
		CaseArtefact() { int x = 12; }
		~CaseArtefact() {}
	private :
		int nbArtefacts;

	}; 
	//EXTERNC DLL CaseArtefact* CASEARTEFACT_New() { return new CaseArtefact(); }
	EXTERNC DLL void CASEARTEFACT_Delete(CaseArtefact* obj) { delete obj; }
} 

