//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#pragma once
#define WANTDLLEXP
#ifdef WANTDLLEXP		//exportation dll
#define DLL  __declspec( dllexport )
#define EXTERNC extern "C"
#else
#define DLL		//standard
#define EXTERNC
#endif
#include "Case.h"
#include<vector>

namespace Model
{
	/// <remarks>Poids mouche</remarks>
	class DLL CaseVide : public Case
	{
	public:
		CaseVide() {}
		~CaseVide() {}
	}; 
	//EXTERNC DLL CaseVide* CASEVIDE_New() { return new CaseVide(); }
	EXTERNC DLL void CASEVIDE_Delete(CaseVide* obj) { delete obj; }
} 

