//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#pragma once
#define WANTDLLEXP
#ifdef WANTDLLEXP		//exportation dll
#define DLL  __declspec( dllexport )
#define EXTERNC extern "C"
#else
#define DLL		//standard
#define EXTERNC
#endif
#include "Case.h"
#include<vector>

namespace Model
{
	/// <remarks>Poids mouche</remarks>
	class DLL CaseEnergie : public Case
	{
	public:
		CaseEnergie() {}
		~CaseEnergie() {}
	}; 
	//EXTERNC DLL CaseEnergie* CASEENERGIE_New() { return new CaseEnergie(); }
	EXTERNC DLL void CASEENERGIE_Delete(CaseEnergie* obj) { delete obj; }
} 

