//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#pragma once
#define WANTDLLEXP
#ifdef WANTDLLEXP		//exportation dll
#define DLL  __declspec( dllexport )
#define EXTERNC extern "C"
#else
#define DLL		//standard
#define EXTERNC
#endif
#include<vector>

namespace Model
{
	class DLL Des 
	{
		private :

			std::vector<int> faces;

		public :
			Des() {}
			~Des() {}
			int lancer() { return 5; }

	}; 
	
	EXTERNC DLL Des* DES_New() { return new Des(); }
	EXTERNC DLL void DES_Delete(Des* obj) { delete obj; }
	EXTERNC DLL int DES_lancer(Des* d) { return d->lancer(); }
} 

