//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Model
{

	enum Direction
	{
		BAS_HAUT,
		HAUT_BAS,
		DIAGONAL_HVB_GVD,
		DIAGONAL_BVH_GVD,
		GAUCHE_DROITE,
		DROITE_GAUCHE,
		DIAGONAL_BVH_DVG,
		DIAGONAL_HVB_DVG,
	};
}
