//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#pragma once
#define WANTDLLEXP
#ifdef WANTDLLEXP		//exportation dll
#define DLL  __declspec( dllexport )
#define EXTERNC extern "C"
#else
#define DLL		//standard
#define EXTERNC
#endif
#include "FabriqueCaseAbs.h"
#include<vector>

namespace Model
{
	class DLL FabriqueCase : public FabriqueCaseAbs
	{
		public :
			FabriqueCase() {}
			~FabriqueCase() {}
			virtual CaseArtefact* fabriquerCaseArtefact() { return new CaseArtefact(); }
			virtual CaseAsteroide* fabriquerCaseAsteroide()  { return new CaseAsteroide(); }
			virtual CaseBase* fabriquerCaseBase(Joueur j)  { return new CaseBase(); }
			virtual CaseEnergie* fabriquerCaseEnergie()  { return new CaseEnergie(); }
			virtual CaseVide* fabriquerCaseVide() { return new CaseVide(); }

	}; 

	EXTERNC DLL FabriqueCase* FABRIQUECASE_New() { return new FabriqueCase(); }
	EXTERNC DLL void FABRIQUECASE_Delete(FabriqueCase* obj) { delete obj; }
	EXTERNC DLL CaseArtefact* FABRIQUECASE_fabriquerCaseArtefact(FabriqueCase* fab) { return fab->fabriquerCaseArtefact(); }
	EXTERNC DLL CaseAsteroide* FABRIQUECASE_fabriquerCaseAsteroide(FabriqueCase* fab) { return fab->fabriquerCaseAsteroide(); }
	EXTERNC DLL CaseBase* FABRIQUECASE_fabriquerCaseBase(FabriqueCase* fab, Joueur j) { return fab->fabriquerCaseBase(j); }
	EXTERNC DLL CaseEnergie* FABRIQUECASE_fabriquerCaseEnergie(FabriqueCase* fab) { return fab->fabriquerCaseEnergie(); }
	EXTERNC DLL CaseVide* FABRIQUECASE_fabriquerCaseVide(FabriqueCase* fab) { return fab->fabriquerCaseVide(); }
} 

