//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#pragma once
#define WANTDLLEXP
#ifdef WANTDLLEXP		//exportation dll
#define DLL  __declspec( dllexport )
#define EXTERNC extern "C"
#else
#define DLL		//standard
#define EXTERNC
#endif

#include "Joueur.h"
#include "CaseArtefact.h"
#include "CaseAsteroide.h"
#include "CaseBase.h"
#include "CaseEnergie.h"
#include "CaseVide.h"

namespace Model
{
	/// <remarks>Poids mouche</remarks>
	class DLL FabriqueCaseAbs 
	{
	public:
		virtual CaseArtefact* fabriquerCaseArtefact()=0;

		virtual CaseAsteroide* fabriquerCaseAsteroide()=0;

		virtual CaseBase* fabriquerCaseBase(Joueur j)=0;

		virtual CaseEnergie* fabriquerCaseEnergie()=0;

		virtual CaseVide* fabriquerCaseVide()=0;

	};

	/*EXTERNC DLL CaseArtefact* FABRIQUECASEABS_fabriquerCaseArtefact();
	EXTERNC DLL CaseAsteroide* FABRIQUECASEABS_fabriquerCaseAsteroide();
	EXTERNC DLL CaseBase* FABRIQUECASEABS_fabriquerCaseBase(Joueur);
	EXTERNC DLL CaseEnergie* FABRIQUECASEABS_fabriquerCaseEnergie();
	EXTERNC DLL CaseVide* FABRIQUECASEABS_fabriquerCaseVide();*/
}

