//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#pragma once
#define WANTDLLEXP
#ifdef WANTDLLEXP		//exportation dll
#define DLL  __declspec( dllexport )
#define EXTERNC extern "C"
#else
#define DLL		//standard
#define EXTERNC
#endif
#include "Joueur.h"
#include "Plateau.h"
#include "Des.h"
#include<vector>

namespace Model
{
	class DLL Jeu 
	{
		private :

			Joueur joueurCourant;
			std::vector<Joueur> joueurs;
			Plateau plateau;
			std::vector<Des> des;

		public :
			Jeu() {}
			~Jeu() {}
			virtual void lancerPartie() {}
			virtual void prochainJoueur() {}
			virtual void finPartie() {}

	}; 

	EXTERNC DLL Jeu* JEU_New() { return new Jeu(); }
	EXTERNC DLL void JEU_Delete(Jeu* obj) { delete obj; }
	EXTERNC DLL void JEU_lancerPartie(Jeu* j) { j->lancerPartie(); }
	EXTERNC DLL void JEU_prochainJoueur(Jeu* j) { j->prochainJoueur(); }
	EXTERNC DLL void JEU_finPartie(Jeu* j) { j->finPartie(); }
} 

