//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#pragma once
#define WANTDLLEXP
#ifdef WANTDLLEXP		//exportation dll
#define DLL  __declspec( dllexport )
#define EXTERNC extern "C"
#else
#define DLL		//standard
#define EXTERNC
#endif
#include<vector>

namespace Model
{
	class DLL Laser
	{
	private :
		int nombreRebondsRestants;
		std::vector<float*> pointsDePassage;
		float angleCourant;
			
		void calculProchainRebond();

	public :
		Laser() {}
		~Laser() {}
		virtual void calculTrajectoire() {}

	}; 

	EXTERNC DLL Laser* LASER_New() { return new Laser(); }
	EXTERNC DLL void LASER_Delete(Laser* obj) { delete obj; }
	EXTERNC DLL void LASER_calculTrajectoire(Laser* l) { l->calculTrajectoire(); }
} 

