//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#pragma once
#define WANTDLLEXP
#ifdef WANTDLLEXP		//exportation dll
#define DLL  __declspec( dllexport )
#define EXTERNC extern "C"
#else
#define DLL		//standard
#define EXTERNC
#endif
#include "MonteurJeu.h"
#include<vector>

namespace Model
{
	class DLL MonteurJeu4J : public MonteurJeu
	{
	public:
		MonteurJeu4J() {}
		~MonteurJeu4J() {}

		virtual void creerPlateau() {}
	}; 

	EXTERNC DLL MonteurJeu4J*  MONTEURJEU4J_New() { return new MonteurJeu4J(); }
	EXTERNC DLL void MONTEURJEU4J_Delete(MonteurJeu4J* obj) { delete obj; }
} 

