//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#pragma once
#define WANTDLLEXP
#ifdef WANTDLLEXP		//exportation dll
#define DLL  __declspec( dllexport )
#define EXTERNC extern "C"
#else
#define DLL		//standard
#define EXTERNC
#endif
#include "MonteurJeu.h"
#include<vector>

namespace Model
{
	class DLL MonteurJeu2J : public MonteurJeu
	{
	public:
		MonteurJeu2J() {}
		~MonteurJeu2J() {}

		virtual void creerPlateau() {}
	}; 

	EXTERNC DLL MonteurJeu2J*  MONTEURJEU2J_New() { return new MonteurJeu2J(); }
	EXTERNC DLL void MONTEURJEU2J_Delete(MonteurJeu2J* obj) { delete obj; }
} 

