//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#pragma once
#define WANTDLLEXP
#ifdef WANTDLLEXP		//exportation dll
#define DLL  __declspec( dllexport )
#define EXTERNC extern "C"
#else
#define DLL		//standard
#define EXTERNC
#endif

#include <vector>
#include "CanonLaser.h"
#include "Joueur.h"

namespace Model
{
	class Vaisseau
	{
	protected:
		int nombreDes;
		std::vector<int> deplacementsImpossibles;
		CanonLaser canonLaser;
		std::vector<int> coordonnees;
		Joueur* proprietaire;


		void collisionAsteroide() {}

	public:
		Vaisseau() : nombreDes(2), deplacementsImpossibles(), canonLaser(this), coordonnees() {
			proprietaire = 0;
		}

		Vaisseau(Joueur& j, int nbDes, std::vector<int> coord) 
			: nombreDes(nbDes), deplacementsImpossibles(), canonLaser(this), coordonnees(coord) {
			proprietaire = &j;
		}

		~Vaisseau() {
			if(proprietaire)
				delete proprietaire;
		}

		virtual void deplacer(int dx, int dy) {}
		virtual void rechargerCanon() {}

	}; 

	/*EXTERNC DLL Vaisseau* VAISSEAU_New() { return new Vaisseau(); }
	EXTERNC DLL void VAISSEAU_Delete(Vaisseau* obj) { delete obj; }*/
	EXTERNC DLL void VAISSEAU_deplacer(Vaisseau* v, int dx, int dy) { v->deplacer(dx, dy); }
	EXTERNC DLL void VAISSEAU_rechargerCanon(Vaisseau* v) { v->rechargerCanon(); }
	//EXTERNC DLL void VAISSEAU_collisionAsteroide(Vaisseau* v){ v->collisionAsteroide(); }
} 

