//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#pragma once
#define WANTDLLEXP
#ifdef WANTDLLEXP		//exportation dll
#define DLL  __declspec( dllexport )
#define EXTERNC extern "C"
#else
#define DLL		//standard
#define EXTERNC
#endif

#include "Transporteur.h"
#include<vector>

namespace Model
{
	class DLL VaisseauMere : public Transporteur
	{
	public:
		VaisseauMere() {}
		~VaisseauMere() {}

	}; 

	EXTERNC DLL VaisseauMere* VAISSEAUMERE_New() { return new VaisseauMere(); }
	EXTERNC DLL void VAISSEAUMERE_Delete(VaisseauMere* obj) { delete obj; }
} 

