//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Vue.Interfaces
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	/// <remarks>Fabrique abstraite</remarks>
	public class FabriqueVuesAbs
	{
		private static FabriqueVue fabrique
		{
			get;
			set;
		}

		public virtual FabriqueVue FabriqueVueLaser
		{
			get;
			set;
		}

		public static void setFabrique(FabriqueVue f)
		{
			throw new System.NotImplementedException();
		}

		public static void getFabrique()
		{
			throw new System.NotImplementedException();
		}

	}
}

