//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Vue.Interfaces
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
using System.Drawing;

	/// <remarks>Fabrique abstraite</remarks>
	public interface FabriqueVue 
	{
		void creerLaser();

		void creerCaseArtefact(int nbArtefacts);

		void creerVaisseauMere();

		void creerDes();

		void creerCaseBase(Color couleur);

		void creerCaseAsteroide(int[] points);

		void creerCaseVide();

		void creerCaseEnergie();

		void creerBattlecruiser();

		void creerCapsuleDeSurvie();

		void creerVueQuitter();

		void creerCompteurArtefact();

		void creerCompteurCanon();

	}
}

