//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Controleur.instrument
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class BoutonQuitter : Instrument
	{
		public virtual void boutonPresse()
		{
			throw new System.NotImplementedException();
		}

	}
}

