//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Controleur.instrument
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class CurseurPlateau : Instrument
	{
		public virtual void sourisPressee(double x, double y)
		{
			throw new System.NotImplementedException();
		}

		public virtual void sourisPrRelachee(double x, double y)
		{
			throw new System.NotImplementedException();
		}

		public virtual void sourisBougee()
		{
			throw new System.NotImplementedException();
		}

	}
}

