//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Controleur.instrument
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	/// <remarks>Memento</remarks>
	public class UndoRedoManager : Instrument
	{
		public virtual void actionUndo()
		{
			throw new System.NotImplementedException();
		}

		public virtual void actionRedo()
		{
			throw new System.NotImplementedException();
		}

	}
}

