//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Vue.Impl2D
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
	using Vue.Interfaces;

	public class FenetreAccueil2D : FenetreAccueil
	{
		public virtual VueChoixJoueurs VueChoixJoueurs
		{
			get;
			set;
		}

		public virtual VueCredits VueCredits
		{
			get;
			set;
		}

		public virtual void update()
		{
			throw new System.NotImplementedException();
		}

		public virtual void afficherChoixJoueur()
		{
			throw new System.NotImplementedException();
		}

		public virtual void afficherCredits()
		{
			throw new System.NotImplementedException();
		}

	}
}

