//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Vue.Impl2D
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
	using Vue.Interfaces;
    using System.Drawing;

	public class VueCredits2D : VueCredits
	{
        public Color couleur
        {
            get {return couleur;}
            set { couleur = value; }
        }

	}
}

