//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Vue.Impl2D
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
	using Vue.Interfaces;

	public class VueCompteurArtefacts2D : VueComposantTableauDeBord2D, VueCompteurArtefacts
	{
		public override void update()
		{
			throw new System.NotImplementedException();
		}

		public virtual void augmenterNbArtefacts()
		{
			throw new System.NotImplementedException();
		}

	}
}

