//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Vue.Impl2D
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
	using Vue;
	using Vue.Interfaces;
    using System.Drawing;

	public class VueCase2D : VueCase
	{
		private Color couleur
		{
			get;
			set;
		}

		public virtual void update()
		{
			throw new System.NotImplementedException();
		}

		public virtual void illuminer()
		{
			throw new System.NotImplementedException();
		}

	}
}

