//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Vue.Impl2D
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
	using Vue.Interfaces;

	public class VueVaisseau2D : VueVaisseau
	{
		public virtual VueArtefact VueArtefact
		{
			get;
			set;
		}

		public virtual void update()
		{
			throw new System.NotImplementedException();
		}

		public virtual void deplacer(int x, int y)
		{
			throw new System.NotImplementedException();
		}

		public virtual void changerOrientation(float angle)
		{
			throw new System.NotImplementedException();
		}

		public virtual void chargerUnArtefact()
		{
			throw new System.NotImplementedException();
		}

	}
}

